org.gradle.jvmargs=-Xmx4g -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1g
org.gradle.daemon=true
org.gradle.workers.max=4
org.gradle.parallel=true
android.useAndroidX=true
#org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m
#org.gradle.daemon=false
#org.gradle.workers.max=1
#org.gradle.parallel=false
#android.useAndroidX=true